# Generated by Django 4.2.6 on 2023-10-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivermail',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
