# Generated by Django 4.2.7 on 2023-11-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_receivermail_options_alter_receivermail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendermailaddress',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
